"use client";
import { useState } from "react";
import { isConnectivityTestArtifact, meaningfulMemoryCount, parseGameMemory } from "@/lib/memory/game-memory";
import { MEMORY_PREFERENCE_STORAGE_KEY, normalizeMemoryPreference } from "@/lib/memory/memory-preference";
import type { PlayerMemoryProfile } from "@/lib/memory/player-profile";
import type { PlayerProfile } from "@/lib/memory/players";
type Recall = { ok: boolean; error?: string; memories?: Array<{ blobId: string; text: string }>; total?: number };
type Profile = { ok: boolean; status?: string; error?: string; profile?: PlayerMemoryProfile | null; qwenUsed?: boolean; qwenError?: string | null };
export function MemoryInspector({ activePlayer }: { activePlayer: PlayerProfile }) {
  const [recall, setRecall] = useState<Recall | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [loading, setLoading] = useState(false);
  const memoryOn = () => normalizeMemoryPreference(window.localStorage.getItem(MEMORY_PREFERENCE_STORAGE_KEY)) === "on";
  const loadRecall = async () => { setLoading(true); try { setRecall(await (await fetch("/api/memory/recall", { cache: "no-store" })).json() as Recall); } catch { setRecall({ ok: false, error: "Recall request failed." }); } finally { setLoading(false); } };
  const loadProfile = async () => { setLoading(true); try { setProfile(await (await fetch(`/api/memory/profile?memory=${memoryOn() ? "on" : "off"}`, { cache: "no-store" })).json() as Profile); } catch { setProfile({ ok: false, error: "Profile request failed." }); } finally { setLoading(false); } };
  const memories = recall?.memories ?? []; const meaningful = meaningfulMemoryCount(memories.map((item) => item.text)); const artifacts = memories.filter((item) => isConnectivityTestArtifact(item.text)).length;
  return <section className="rounded-3xl border border-amber-300 bg-amber-50 p-5"><p className="text-xs font-bold uppercase text-amber-800">Development only</p><h2 className="text-lg font-black">Memory Inspector</h2><p className="mt-1 text-sm">Active: {activePlayer.displayName} · <span className="font-mono">whoamai:{activePlayer.id}</span></p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={loadRecall} disabled={loading} className="min-h-11 rounded-xl bg-amber-400 px-4 font-bold">Recall memories</button><button type="button" onClick={loadProfile} disabled={loading} className="min-h-11 rounded-xl border border-amber-500 px-4 font-bold">Build player profile</button></div>{recall?.ok && <div className="mt-4 rounded-xl bg-white p-3"><p>Meaningful gameplay memories: <strong>{meaningful}</strong> · Connectivity-test artifacts: <strong>{artifacts}</strong></p>{memories.map((memory) => { const parsed = parseGameMemory(memory.text); return <p key={memory.blobId} className="mt-2 text-sm">{parsed ? `${parsed.type}: ${parsed.text} (game ${parsed.gameId})` : isConnectivityTestArtifact(memory.text) ? "Connectivity-test artifact" : "Unknown/malformed recalled record"} · <span className="font-mono text-xs">{memory.blobId}</span></p>; })}</div>}{profile && <div className="mt-4 rounded-xl bg-white p-3"><h3 className="font-black">PLAYER MEMORY PROFILE</h3>{profile.status === "memory_off" ? <p className="mt-2">Memory is OFF — no Walrus recall or Qwen interpretation was requested.</p> : profile.ok && profile.profile ? <><p className="mt-2">Meaningful memories: {profile.profile.meaningfulMemoryCount} · Completed games: {profile.profile.completedGameCount} · Evidence: {profile.profile.evidenceQuality}</p>{profile.profile.knownResults.map((result) => <p key={result.gameId} className="text-sm">Known result: {result.outcome} against {result.characterId} in {result.actions} actions</p>)}<p className="mt-2 text-sm">Established observations: {profile.profile.establishedObservations.length}; proposed interpretations: {profile.profile.proposedInterpretations.length}.</p>{profile.qwenError && <p className="text-sm text-slate-600">{profile.qwenError}</p>}</> : <p>{profile.error ?? "Profile unavailable."}</p>}</div>}</section>;
}
