import { MemWal } from "@mysten-incubation/memwal";
import { namespaceForPlayer } from "../src/lib/memory/players.ts";

const required = (name: "MEMWAL_PRIVATE_KEY" | "MEMWAL_ACCOUNT_ID") => { const value = process.env[name]?.trim(); if (!value) throw new Error(`${name} is required.`); return value; };
const serverUrl = process.env.MEMWAL_SERVER_URL?.trim() || "https://relayer.memory.walrus.xyz";
const create = (player: "player_aaron" | "player_leo") => MemWal.create({ key: required("MEMWAL_PRIVATE_KEY"), accountId: required("MEMWAL_ACCOUNT_ID"), serverUrl, namespace: namespaceForPlayer(player) });
const marker = (player: string) => `[WHOAMAI_CONNECTIVITY_TEST] ${player} connectivity marker ${Date.now()}-${Math.random().toString(36).slice(2)}`;
const contains = (result: { results: Array<{ text: string }> }, text: string) => result.results.some((item) => item.text === text);
async function main() { const aaron = create("player_aaron"); const leo = create("player_leo"); const health = await aaron.health(); console.log(`Network: mainnet\nRelayer health: PASS (${Object.keys(health).join(", ")})`); const aaronMarker = marker("Aaron"); const aaronAccepted = await aaron.remember(aaronMarker); const aaronDone = await aaron.waitForRememberJob(aaronAccepted.job_id, { timeoutMs: 120_000 }); console.log(`Authenticated Aaron write: PASS\nAaron namespace: ${namespaceForPlayer("player_aaron")}\nAaron job ID: ${aaronAccepted.job_id}\nAaron blob ID: ${aaronDone.blob_id}`); const aaronRecall = await aaron.recall({ query: aaronMarker, limit: 10 }); if (!contains(aaronRecall, aaronMarker)) throw new Error("Aaron recall did not contain its exact marker."); const leoMarker = marker("Leo"); const leoAccepted = await leo.remember(leoMarker); const leoDone = await leo.waitForRememberJob(leoAccepted.job_id, { timeoutMs: 120_000 }); console.log(`Authenticated Leo write: PASS\nLeo namespace: ${namespaceForPlayer("player_leo")}\nLeo job ID: ${leoAccepted.job_id}\nLeo blob ID: ${leoDone.blob_id}`); const leoRecall = await leo.recall({ query: leoMarker, limit: 10 }); if (!contains(leoRecall, leoMarker)) throw new Error("Leo recall did not contain its exact marker."); const aaronForeign = await aaron.recall({ query: leoMarker, limit: 10 }); const leoForeign = await leo.recall({ query: aaronMarker, limit: 10 }); if (contains(aaronForeign, leoMarker) || contains(leoForeign, aaronMarker)) throw new Error("Exact foreign marker leaked across namespaces."); console.log("Aaron recall: PASS\nLeo recall: PASS\nAaron -> Leo isolation: PASS\nLeo -> Aaron isolation: PASS\nOverall: PASS"); }
main().catch((error: unknown) => { console.error(error instanceof Error ? error.message : "Walrus Memory connectivity test failed."); process.exitCode = 1; });
