import assert from "node:assert/strict";
import test from "node:test";
import { rankChallengeCandidates } from "./challenge-ranking.ts";
import { FIXTURE_CONNECTIVITY, FIXTURE_MALFORMED, FIXTURE_ONE, FIXTURE_THREE, FIXTURE_UNKNOWN } from "./profile-fixtures.ts";
import { buildPlayerMemoryProfile, classifyRecalledMemoryTexts } from "./player-profile.ts";
import { parseProfileRequest } from "./profile-request.ts";
import { canUsePersonalization } from "./personalization-policy.ts";
import { parseGameMemory } from "./game-memory.ts";

test("excludes connectivity and malformed records while aggregating one factual result", () => { const profile = buildPlayerMemoryProfile("player_aaron", [FIXTURE_CONNECTIVITY, FIXTURE_MALFORMED, FIXTURE_UNKNOWN, FIXTURE_ONE]); assert.equal(profile.meaningfulMemoryCount, 1); assert.equal(profile.completedGameCount, 1); assert.equal(profile.connectivityArtifactCount, 1); assert.equal(profile.invalidRecordCount, 1); assert.equal(profile.evidenceQuality, "results_only"); assert.equal(profile.proposedInterpretations.length, 0); assert.equal(profile.knownResults[0].characterId, "tessa"); });
test("requires evidence for Qwen proposals and establishes only validated observations", () => { const qwen = { observations: [{ type: "STRATEGY", pattern: "headwear", gameIds: ["fixture-one", "fixture-two", "fixture-three"], questionFields: ["hasHeadwear"] }] }; const profile = buildPlayerMemoryProfile("player_aaron", FIXTURE_THREE, qwen); assert.equal(profile.evidenceQuality, "behavior_ready"); assert.equal(profile.proposedInterpretations.length, 1); const invented = buildPlayerMemoryProfile("player_aaron", FIXTURE_THREE, { observations: [{ type: "PREFERENCE", pattern: "headwear", gameIds: ["invented", "fixture-two", "fixture-three"], questionFields: ["hasHeadwear"] }] }); assert.equal(invented.proposedInterpretations.length, 0); });
test("profile request prevents spoofing and OFF prevents personalization recall", () => { assert.equal(parseProfileRequest(new URL("http://localhost/api/memory/profile?namespace=x")).ok, false); assert.deepEqual(parseProfileRequest(new URL("http://localhost/api/memory/profile?memory=off")), { ok: true, memory: "off" }); const profile = buildPlayerMemoryProfile("player_aaron", [FIXTURE_ONE]); assert.equal(canUsePersonalization(profile, false), false); assert.equal(rankChallengeCandidates(profile).status, "neutral"); assert.equal(rankChallengeCandidates(buildPlayerMemoryProfile("player_aaron", FIXTURE_THREE)).status, "history_supported"); });
test("classifies cross-player-looking arbitrary text as unknown, not usable memory", () => { const classified = classifyRecalledMemoryTexts(["Leo won against Tessa in 1 action."]); assert.equal(classified.valid.length, 0); assert.equal(classified.unknown, 1); });
test("keeps established records separate and rejects sensitive or unsupported Qwen vocabulary", () => { const base = parseGameMemory(FIXTURE_ONE)!; const established = `[WHOAMAI_GAME_MEMORY]\n${JSON.stringify({ ...base, type: "STRATEGY", text: "Aaron uses headwear questions often." })}`; const profile = buildPlayerMemoryProfile("player_aaron", [FIXTURE_ONE, established]); assert.equal(profile.establishedObservations.length, 1); assert.equal(profile.proposedInterpretations.length, 0); const sensitive = buildPlayerMemoryProfile("player_aaron", FIXTURE_THREE, { observations: [{ type: "STRATEGY", pattern: "smart", gameIds: ["fixture-one", "fixture-two", "fixture-three"], questionFields: ["hasHeadwear"] }] }); assert.equal(sensitive.proposedInterpretations.length, 0); });
